import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    absolute: "", // template must be ignored when you define absolute property in other pages
    default: "Next.js Tutorial - Codeevolution", // everywhere where not define a title will be place this value
    template: "%s | Codeevoultion", // %s is a variable that we define in other pages
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightblue", padding: "1rem" }}>
          Header
        </header>
        {children}
        <footer style={{ backgroundColor: "ghostwhite", padding: "1rem" }}>
          Footer
        </footer>
      </body>
    </html>
  );
}
